"""Immutable CR 614-616 replacement-event substrate."""

from .applicability import canonical_effects, condition_matches, replacement_choice
from .application import (
    apply_replacement,
    canonical_replacement_selection,
    resolve_replacements,
)
from .immutable import FrozenMap, immutable_fingerprint
from .model import (
    AffectedObject,
    EntryReplacementScope,
    PreventionAllocationChoice,
    ReplaceableEvent,
    ReplacementBatchChoice,
    ReplacementBatchProgress,
    ReplacementChoice,
    ReplacementClass,
    ReplacementEffect,
    ReplacementEffectError,
    ReplacementEventBatch,
    ReplacementSelection,
    ReplacementTreeChoice,
)
from .operations import (
    AddAmount,
    AppendValues,
    CapResultLifeLoss,
    CreateAffectedObjectCounter,
    CreateAdditionalToken,
    CreateResultDraws,
    CreateNestedEvent,
    DredgeDraw,
    GrantAffectedObjectKeyword,
    MultiplyAmount,
    MultiplyTokenCreation,
    PreventAmount,
    PreventDraw,
    PreventUsingShield,
    RedirectDamage,
    ReplacementOperation,
    ReserveZoneChange,
    SetField,
    UnionValues,
    operation_from_dict,
    operation_to_dict,
)
from .ordering import (
    ReplacementChoiceRequired,
    advance_replacement_batch,
    apply_batch_replacement,
    apply_tree_replacement,
    next_batch_replacement_choice,
    replacement_choice_payload,
    replacement_tree_choice,
    resolve_replacement_batch,
)
from .replay import ReplacementContinuation

__all__ = [
    "AddAmount",
    "AffectedObject",
    "AppendValues",
    "CapResultLifeLoss",
    "CreateAffectedObjectCounter",
    "CreateAdditionalToken",
    "CreateResultDraws",
    "CreateNestedEvent",
    "DredgeDraw",
    "EntryReplacementScope",
    "FrozenMap",
    "GrantAffectedObjectKeyword",
    "MultiplyAmount",
    "MultiplyTokenCreation",
    "PreventAmount",
    "PreventDraw",
    "PreventUsingShield",
    "PreventionAllocationChoice",
    "ReplaceableEvent",
    "ReplacementBatchChoice",
    "ReplacementBatchProgress",
    "ReplacementChoice",
    "ReplacementChoiceRequired",
    "ReplacementClass",
    "ReplacementContinuation",
    "ReplacementEffect",
    "ReplacementEffectError",
    "ReplacementEventBatch",
    "ReplacementOperation",
    "ReplacementSelection",
    "ReplacementTreeChoice",
    "RedirectDamage",
    "ReserveZoneChange",
    "SetField",
    "UnionValues",
    "advance_replacement_batch",
    "apply_batch_replacement",
    "apply_replacement",
    "apply_tree_replacement",
    "canonical_effects",
    "canonical_replacement_selection",
    "condition_matches",
    "immutable_fingerprint",
    "next_batch_replacement_choice",
    "operation_from_dict",
    "operation_to_dict",
    "replacement_choice",
    "replacement_choice_payload",
    "replacement_tree_choice",
    "resolve_replacement_batch",
    "resolve_replacements",
]
