from __future__ import annotations

from functools import lru_cache

from ..rules.capabilities import load_default_capability_registry
from .activated_abilities import (
    ACTIVATED_ABILITY_CATALOG_HANDLER_ID,
    ActivatedAbilityCatalogHandler,
    ActivatedAbilityCatalogRegistry,
    activated_abilities_from_descriptors,
    activated_ability_catalog_descriptor,
    default_activated_ability_catalog_registry,
    is_structural_activated_ability_catalog_program,
)
from .ability_fragments import (
    BATTLE_CRY_FRAGMENT_HANDLER_ID,
    BUSHIDO_FRAGMENT_HANDLER_ID,
    DECLARATION_COST_FRAGMENT_HANDLER_ID,
    DECLARATION_REQUIREMENT_FRAGMENT_HANDLER_ID,
    DECLARATION_RESTRICTION_FRAGMENT_HANDLER_ID,
    ENCHANT_FRAGMENT_HANDLER_ID,
    TYPED_ENCHANT_FRAGMENT_HANDLER_ID,
    EXALTED_FRAGMENT_HANDLER_ID,
    FLANKING_FRAGMENT_HANDLER_ID,
    MELEE_FRAGMENT_HANDLER_ID,
    PROTECTION_FRAGMENT_HANDLER_ID,
    BattleCryAbilityFragmentHandler,
    BushidoAbilityFragmentHandler,
    DeclarationCostAbilityFragmentHandler,
    DeclarationRequirementAbilityFragmentHandler,
    DeclarationRestrictionAbilityFragmentHandler,
    ExaltedAbilityFragmentHandler,
    FlankingAbilityFragmentHandler,
    MeleeAbilityFragmentHandler,
    TypedEnchantAbilityFragmentHandler,
    default_ability_fragment_registry,
    fragments_from_descriptors,
)
from .context import (
    ReadOnlyHandlerContext,
    ReadOnlyRulesQuery,
    SemanticNodeError,
    SemanticSourceContext,
    semantic_source_context,
)
from .components import (
    describe_runtime_handler,
    runtime_component_inventory,
    runtime_component_registry_fingerprint,
    validate_runtime_handler_descriptors,
)
from .unearth import (
    default_ordinary_unearth_ability_registry,
    OrdinaryUnearthAbilityHandler,
    OrdinaryUnearthAbilityRegistry,
    ordinary_unearth_specs_from_descriptors,
    UNEARTH_EFFECT_HANDLERS,
    UnearthEffectHandler,
)
from .self_zone_move import SELF_ZONE_MOVE_EFFECT_HANDLERS
from .cast_permissions import (
    CastPermissionRegistry,
    default_cast_permission_registry,
    FLASH_CAST_PERMISSION_HANDLER_ID,
    FlashCastPermissionHandler,
)
from .cast_costs import (
    AFFINITY_HANDLER_ID,
    AffinityCostHandler,
    AffinitySpec,
    CONVOKE_COST_EVENT,
    CONVOKE_HANDLER_ID,
    CastCostComponentRegistry,
    ConvokeCostHandler,
    affinity_handler_descriptor,
    default_cast_cost_component_registry,
)
from .continuous_components import (
    AddBasicLandTypeHandler,
    AddBasicLandTypeNode,
    ContinuousEffectComponentRegistry,
    ContinuousEffectSourceContext,
    FixedQueryAbilityGrantHandler,
    FixedQueryAbilityGrantNode,
    FixedPowerToughnessAnthemHandler,
    FixedPowerToughnessAnthemNode,
    FixedQueryPowerToughnessAnthemHandler,
    FixedQueryPowerToughnessAnthemNode,
    default_continuous_effect_component_registry,
)
from .attached_continuous import (
    ATTACHED_FIXED_CHARACTERISTICS_HANDLER_ID,
    AttachedFixedCharacteristicsHandler,
    AttachedFixedCharacteristicsNode,
)
from .counter_replacements import (
    collect_counter_placement_replacement_effects,
    CounterPlacementEventSpec,
    CounterPlacementReplacementRegistry,
    CounterPlacementReplacementResolution,
    CounterQuantityReplacementHandler,
    CounterQuantityReplacementNode,
    CounterQuantityReplacementV2Handler,
    CounterQuantityReplacementV2Node,
    CounterReplacementSourceContext,
    default_counter_placement_replacement_registry,
    resolve_counter_placement_replacements,
)
from .counter_placement_handlers import (
    COUNTER_PLACEMENT_HANDLERS,
    FixedCounterPlacementHandler,
    FixedCounterPlacementBatchHandler,
    FixedCounterPlacementSetHandler,
    FixedCounterPlacementTargetSetHandler,
    FixedPlayerCounterPlacementHandler,
)
from .counter_removal_handlers import (
    AllCounterRemovalHandler,
    COUNTER_REMOVAL_HANDLERS,
    FixedCounterRemovalHandler,
)
from .damage_replacements import (
    AllDamagePreventionHandler,
    AllDamagePreventionNode,
    AllDamagePreventionScopeNode,
    collect_damage_replacement_effects,
    DamageQuantityReplacementHandler,
    DamageQuantityReplacementNode,
    DamageQuantityReplacementV2Handler,
    DamageReplacementCondition,
    DamageReplacementRegistry,
    DamageReplacementSourceContext,
    default_damage_replacement_registry,
    FixedDamagePreventionHandler,
    FixedDamagePreventionNode,
    StaticDamageRedirectionHandler,
    StaticDamageRedirectionNode,
)
from .damage_results import (
    collect_damage_result_replacement_effects,
    DamageResultLifeFloorHandler,
    DamageResultLifeFloorNode,
    DamageResultReplacementRegistry,
    DamageResultReplacementSourceContext,
    default_damage_result_replacement_registry,
)
from .draw_replacements import (
    collect_draw_instruction_replacement_effects,
    collect_draw_replacement_effects,
    default_draw_replacement_registry,
    DREDGE_HANDLER_ID,
    DRAW_INSTRUCTION_MULTIPLIER_HANDLER_ID,
    DRAW_RESULT_MULTIPLIER_HANDLER_ID,
    DredgeReplacementHandler,
    DredgeReplacementNode,
    DrawInstructionMultiplierHandler,
    DrawInstructionMultiplierNode,
    DrawInstructionReplacementSourceContext,
    DrawResultMultiplierHandler,
    DrawResultMultiplierNode,
    DrawReplacementRegistry,
    DrawReplacementSourceContext,
)
from .draw_restrictions import (
    collect_draw_restrictions,
    current_draw_permission,
    default_draw_restriction_registry,
    DRAW_MAXIMUM_HANDLER_ID,
    DrawMaximumHandler,
    DrawMaximumNode,
    DrawRestrictionRegistry,
    DrawRestrictionSourceContext,
)
from .draw_reveals import (
    collect_draw_reveal_policies,
    default_draw_reveal_registry,
    DRAW_REVEAL_FIRST_HANDLER_ID,
    DrawRevealFirstHandler,
    DrawRevealFirstNode,
    DrawRevealPolicy,
    DrawRevealRegistry,
    DrawRevealSourceContext,
)
from .life_replacements import (
    collect_life_change_replacement_effects,
    default_life_replacement_registry,
    LifeGainMultiplierHandler,
    LifeGainMultiplierNode,
    LifeReplacementRegistry,
    LifeReplacementSourceContext,
)
from .untap_steps import (
    collect_untap_step_participations,
    current_untap_step_plan,
    default_untap_step_component_registry,
    StaticUntapStepParticipationHandler,
    UNTAP_STEP_HANDLER_ID,
    UntapStepComponentRegistry,
    UntapStepNode,
    UntapStepSourceContext,
)
from .executor import (
    DrawResolutionBatch,
    DrawResolutionRequest,
    SemanticIntentSink,
    draw_resolution_batch,
    execute_intent_plan,
    prepare_draw_resolution,
)
from .effect_handlers import DOMAIN_EFFECT_HANDLERS, DomainEffectHandler
from .destruction_handlers import (
    DESTRUCTION_HANDLERS,
    DestroyPermanentHandler,
    DestroyPermanentSetHandler,
)
from .regeneration_handlers import (
    CreateRegenerationShieldHandler,
    REGENERATION_HANDLERS,
)
from .permanent_exile_handlers import (
    ExilePermanentHandler,
    PERMANENT_EXILE_HANDLERS,
)
from .public_zone_move_handlers import (
    ExilePublicGraveyardCardHandler,
    MovePublicZoneSetHandler,
    PUBLIC_ZONE_MOVE_HANDLERS,
)
from .fixed_damage_set_handlers import (
    FIXED_DAMAGE_SET_HANDLERS,
    FixedDamageSetHandler,
)
from .fixed_target_set_handlers import (
    DestroyPermanentTargetSetHandler,
    FIXED_TARGET_SET_HANDLERS,
    MoveFixedTargetSetHandler,
    SetFixedTargetSetTappedHandler,
)
from .impulse_access_handlers import (
    FixedImpulseAccessHandler,
    IMPULSE_ACCESS_HANDLERS,
)
from .return_to_hand_handlers import (
    RETURN_TO_HAND_HANDLERS,
    ReturnGraveyardCardToOwnerHandHandler,
    ReturnPermanentToOwnerHandHandler,
)
from .stack_counter_handlers import (
    CounterStackTargetHandler,
    STACK_COUNTER_HANDLERS,
)
from .generic import GENERIC_HANDLERS
from .handlers import SemanticNodeHandler
from .intents import (
    AddManaIntent,
    AddSubtypeIntent,
    BecomeMonstrousIntent,
    BecomeRenownedIntent,
    BecomeMonarchIntent,
    CounterStackIntent,
    CopyControlledTokensIntent,
    CopyStackItemIntent,
    ChooseOneRestBottomRandomIntent,
    CreateTokenIntent,
    DealFixedDamageSetIntent,
    DrawCardsIntent,
    MillCardsIntent,
    ImpulseAccessIntent,
    DomainEffectIntent,
    DestroyPermanentIntent,
    DestroyPermanentSetIntent,
    DestroyPermanentTargetsIntent,
    CreateRegenerationShieldIntent,
    IntentPlan,
    EliminatePlayersIntent,
    ExploreCompletedIntent,
    GrantZoneObjectKeywordIntent,
    ExilePermanentIntent,
    ExilePublicGraveyardCardIntent,
    LifeChangeIntent,
    LibrarySelectionIntent,
    MoveObjectsSimultaneouslyIntent,
    MadnessChoiceIntent,
    MovePublicZoneSetIntent,
    MoveLibraryCardsToBottomIntent,
    ScryLibraryIntent,
    SurveilLibraryIntent,
    PayManaCostIntent,
    PayLifeIntent,
    CounterPlacementAmount,
    PlaceCounterBatchIntent,
    PlaceCountersIntent,
    PlaceCountersOnSetIntent,
    PlaceCountersOnTargetsIntent,
    PlacePlayerCountersIntent,
    RemoveAllCountersIntent,
    RemoveCountersIntent,
    RecordChoiceIntent,
    RecordZoneMoveIntent,
    ReturnCardsToLibraryTopIntent,
    ReturnGraveyardCardToOwnerHandIntent,
    ReturnPermanentToOwnerHandIntent,
    ReorderLibraryTopIntent,
    RetargetStackItemIntent,
    RevealLibraryCardsIntent,
    SetCardDesignationIntent,
    SetPermanentTappedIntent,
    SetPermanentsTappedIntent,
    ShuffleLibraryIntent,
    UntapAllCreaturesIntent,
    ZoneMoveIntent,
    ProliferateIntent,
    ProliferateSubject,
)
from .interpreter import SemanticInterpreter
from .nodes import (
    BecomeMonarchNode,
    DrawEachPlayerNode,
    DrawNode,
    SetPermanentTappedNode,
    UntapAllCreaturesNode,
)
from .registry import (
    SemanticHandlerRegistry,
    SemanticHandlerRegistryError,
)
from .token_replacements import (
    AdditionalTokenIntent,
    AdditionalTokenReplacementHandler,
    AdditionalTokenReplacementNode,
    GenericAdditionalTokenReplacementHandler,
    TokenCreationReplacementRegistry,
    TokenCreationReplacementContext,
    TokenCreationReplacementResolution,
    TokenDefinition,
    default_token_creation_replacement_registry,
    resolve_token_creation_replacements,
)
from .tap_state_handlers import TAP_STATE_HANDLERS
from .station_handlers import STATION_HANDLERS, StationCounterPlacementHandler
from .zone_object_keyword_handlers import (
    GrantZoneObjectKeywordHandler,
    ZONE_OBJECT_KEYWORD_HANDLERS,
)
from .zone_replacement_model import (
    PreparedZoneChange,
    ZoneChangeReplacementContext,
    ZoneChangeReplacementResolution,
    ZoneChangeReplacementSnapshot,
    ZoneChangeSubjectSnapshot,
    ZoneDestinationIntent,
    ZoneDestinationReplacementNode,
    ZoneReplacementError,
)
from .zone_replacements import (
    capture_zone_change_replacement_snapshot,
    collect_zone_change_replacement_effects,
    log_applied_zone_replacements,
    ZoneChangeReplacementRegistry,
    ZoneDestinationReplacementHandler,
    default_zone_change_replacement_registry,
    typed_entry_life_payment_amount,
    resolve_zone_change_replacements,
    prepare_zone_change_replacement,
    prepare_zone_change_replacement_batch,
    prepare_zone_change_replacement_snapshot,
)


@lru_cache(maxsize=1)
def default_semantic_handler_registry() -> SemanticHandlerRegistry:
    registry = SemanticHandlerRegistry(
        (
            *GENERIC_HANDLERS,
            *TAP_STATE_HANDLERS,
            *DESTRUCTION_HANDLERS,
            *REGENERATION_HANDLERS,
            *PERMANENT_EXILE_HANDLERS,
            *PUBLIC_ZONE_MOVE_HANDLERS,
            *FIXED_DAMAGE_SET_HANDLERS,
            *FIXED_TARGET_SET_HANDLERS,
            *IMPULSE_ACCESS_HANDLERS,
            *RETURN_TO_HAND_HANDLERS,
            *STACK_COUNTER_HANDLERS,
            *COUNTER_PLACEMENT_HANDLERS,
            *COUNTER_REMOVAL_HANDLERS,
            *STATION_HANDLERS,
            *ZONE_OBJECT_KEYWORD_HANDLERS,
            *UNEARTH_EFFECT_HANDLERS,
            *SELF_ZONE_MOVE_EFFECT_HANDLERS,
            *DOMAIN_EFFECT_HANDLERS,
        )
    )
    capabilities = load_default_capability_registry()
    missing = sorted(
        dependency
        for handler in registry.inventory()
        for dependency in handler["capability_dependencies"]
        if capabilities.capability(dependency) is None
    )
    if missing:
        raise SemanticHandlerRegistryError(
            "Semantic handlers reference unknown capabilities: "
            + ", ".join(missing)
        )
    return registry.freeze()


@lru_cache(maxsize=1)
def default_semantic_interpreter() -> SemanticInterpreter:
    return SemanticInterpreter(default_semantic_handler_registry())


__all__ = [
    "ACTIVATED_ABILITY_CATALOG_HANDLER_ID",
    "ActivatedAbilityCatalogHandler",
    "ActivatedAbilityCatalogRegistry",
    "activated_abilities_from_descriptors",
    "activated_ability_catalog_descriptor",
    "default_activated_ability_catalog_registry",
    "is_structural_activated_ability_catalog_program",
    "ATTACHED_FIXED_CHARACTERISTICS_HANDLER_ID",
    "AttachedFixedCharacteristicsHandler",
    "AttachedFixedCharacteristicsNode",
    "AddBasicLandTypeHandler",
    "AddBasicLandTypeNode",
    "AddManaIntent",
    "AddSubtypeIntent",
    "BecomeMonstrousIntent",
    "BecomeRenownedIntent",
    "BecomeMonarchIntent",
    "CounterStackIntent",
    "CounterStackTargetHandler",
    "CopyControlledTokensIntent",
    "CopyStackItemIntent",
    "ChooseOneRestBottomRandomIntent",
    "CreateTokenIntent",
    "DealFixedDamageSetIntent",
    "BecomeMonarchNode",
    "AdditionalTokenIntent",
    "AdditionalTokenReplacementHandler",
    "AdditionalTokenReplacementNode",
    "GenericAdditionalTokenReplacementHandler",
    "DrawCardsIntent",
    "MillCardsIntent",
    "ImpulseAccessIntent",
    "DomainEffectHandler",
    "DomainEffectIntent",
    "DestroyPermanentHandler",
    "DestroyPermanentIntent",
    "DestroyPermanentSetIntent",
    "DestroyPermanentTargetsIntent",
    "DestroyPermanentSetHandler",
    "DestroyPermanentTargetSetHandler",
    "CreateRegenerationShieldHandler",
    "CreateRegenerationShieldIntent",
    "ExilePermanentHandler",
    "ExilePermanentIntent",
    "FixedDamageSetHandler",
    "MoveFixedTargetSetHandler",
    "FixedImpulseAccessHandler",
    "ReturnPermanentToOwnerHandHandler",
    "ReturnGraveyardCardToOwnerHandHandler",
    "ReturnGraveyardCardToOwnerHandIntent",
    "ReturnPermanentToOwnerHandIntent",
    "DrawEachPlayerNode",
    "DrawNode",
    "DrawResolutionBatch",
    "DrawResolutionRequest",
    "ContinuousEffectComponentRegistry",
    "ContinuousEffectSourceContext",
    "CounterPlacementEventSpec",
    "AFFINITY_HANDLER_ID",
    "AffinityCostHandler",
    "AffinitySpec",
    "CONVOKE_COST_EVENT",
    "CONVOKE_HANDLER_ID",
    "CastCostComponentRegistry",
    "CastPermissionRegistry",
    "ConvokeCostHandler",
    "affinity_handler_descriptor",
    "CounterPlacementReplacementRegistry",
    "CounterPlacementReplacementResolution",
    "CounterQuantityReplacementHandler",
    "CounterQuantityReplacementNode",
    "CounterQuantityReplacementV2Handler",
    "CounterQuantityReplacementV2Node",
    "CounterReplacementSourceContext",
    "FixedCounterPlacementHandler",
    "FixedCounterPlacementBatchHandler",
    "FixedCounterPlacementSetHandler",
    "FixedCounterPlacementTargetSetHandler",
    "FixedPlayerCounterPlacementHandler",
    "FixedCounterRemovalHandler",
    "AllCounterRemovalHandler",
    "DamageQuantityReplacementHandler",
    "DamageQuantityReplacementNode",
    "DamageQuantityReplacementV2Handler",
    "DamageReplacementCondition",
    "DamageReplacementRegistry",
    "DamageReplacementSourceContext",
    "DamageResultLifeFloorHandler",
    "DamageResultLifeFloorNode",
    "DamageResultReplacementRegistry",
    "DamageResultReplacementSourceContext",
    "DREDGE_HANDLER_ID",
    "DRAW_INSTRUCTION_MULTIPLIER_HANDLER_ID",
    "DRAW_RESULT_MULTIPLIER_HANDLER_ID",
    "DRAW_MAXIMUM_HANDLER_ID",
    "DRAW_REVEAL_FIRST_HANDLER_ID",
    "DredgeReplacementHandler",
    "DredgeReplacementNode",
    "DrawInstructionMultiplierHandler",
    "DrawInstructionMultiplierNode",
    "DrawInstructionReplacementSourceContext",
    "DrawResultMultiplierHandler",
    "DrawResultMultiplierNode",
    "DrawMaximumHandler",
    "DrawMaximumNode",
    "DrawRevealFirstHandler",
    "DrawRevealFirstNode",
    "DrawRevealPolicy",
    "DrawRevealRegistry",
    "DrawRevealSourceContext",
    "DrawRestrictionRegistry",
    "DrawRestrictionSourceContext",
    "DrawReplacementRegistry",
    "DrawReplacementSourceContext",
    "collect_draw_reveal_policies",
    "default_draw_reveal_registry",
    "FixedQueryAbilityGrantHandler",
    "FixedQueryAbilityGrantNode",
    "FixedPowerToughnessAnthemHandler",
    "FixedPowerToughnessAnthemNode",
    "FixedQueryPowerToughnessAnthemHandler",
    "FixedQueryPowerToughnessAnthemNode",
    "FLASH_CAST_PERMISSION_HANDLER_ID",
    "FlashCastPermissionHandler",
    "FixedDamagePreventionHandler",
    "FixedDamagePreventionNode",
    "AllDamagePreventionHandler",
    "AllDamagePreventionNode",
    "AllDamagePreventionScopeNode",
    "StaticDamageRedirectionHandler",
    "StaticDamageRedirectionNode",
    "LifeGainMultiplierHandler",
    "LifeGainMultiplierNode",
    "LifeReplacementRegistry",
    "LifeReplacementSourceContext",
    "IntentPlan",
    "EliminatePlayersIntent",
    "ExploreCompletedIntent",
    "GrantZoneObjectKeywordHandler",
    "GrantZoneObjectKeywordIntent",
    "LifeChangeIntent",
    "LibrarySelectionIntent",
    "MoveObjectsSimultaneouslyIntent",
    "MadnessChoiceIntent",
    "MoveLibraryCardsToBottomIntent",
    "ScryLibraryIntent",
    "SurveilLibraryIntent",
    "PayManaCostIntent",
    "PayLifeIntent",
    "CounterPlacementAmount",
    "PlaceCounterBatchIntent",
    "PlaceCountersIntent",
    "PlaceCountersOnSetIntent",
    "PlaceCountersOnTargetsIntent",
    "PlacePlayerCountersIntent",
    "RemoveAllCountersIntent",
    "RemoveCountersIntent",
    "ReadOnlyHandlerContext",
    "RecordChoiceIntent",
    "RecordZoneMoveIntent",
    "ReturnCardsToLibraryTopIntent",
    "ReorderLibraryTopIntent",
    "RetargetStackItemIntent",
    "RevealLibraryCardsIntent",
    "ReadOnlyRulesQuery",
    "SetCardDesignationIntent",
    "SetPermanentTappedIntent",
    "SetPermanentsTappedIntent",
    "SetFixedTargetSetTappedHandler",
    "ShuffleLibraryIntent",
    "SetPermanentTappedNode",
    "SemanticHandlerRegistry",
    "SemanticHandlerRegistryError",
    "SemanticIntentSink",
    "SemanticInterpreter",
    "SemanticNodeHandler",
    "SemanticNodeError",
    "SemanticSourceContext",
    "semantic_source_context",
    "TokenCreationReplacementContext",
    "TokenCreationReplacementRegistry",
    "TokenCreationReplacementResolution",
    "TokenDefinition",
    "UntapAllCreaturesIntent",
    "UNTAP_STEP_HANDLER_ID",
    "UntapStepComponentRegistry",
    "UntapStepNode",
    "UntapStepSourceContext",
    "StaticUntapStepParticipationHandler",
    "ZoneMoveIntent",
    "ProliferateIntent",
    "ProliferateSubject",
    "UntapAllCreaturesNode",
    "ZoneChangeReplacementContext",
    "ZoneChangeReplacementSnapshot",
    "ZoneChangeSubjectSnapshot",
    "ZoneChangeReplacementRegistry",
    "ZoneChangeReplacementResolution",
    "ZoneDestinationIntent",
    "ZoneDestinationReplacementHandler",
    "ZoneDestinationReplacementNode",
    "default_token_creation_replacement_registry",
    "default_continuous_effect_component_registry",
    "default_cast_cost_component_registry",
    "default_cast_permission_registry",
    "default_ability_fragment_registry",
    "default_counter_placement_replacement_registry",
    "default_damage_replacement_registry",
    "default_damage_result_replacement_registry",
    "default_draw_replacement_registry",
    "default_draw_restriction_registry",
    "default_life_replacement_registry",
    "default_untap_step_component_registry",
    "default_semantic_handler_registry",
    "default_semantic_interpreter",
    "default_zone_change_replacement_registry",
    "typed_entry_life_payment_amount",
    "draw_resolution_batch",
    "execute_intent_plan",
    "prepare_draw_resolution",
    "resolve_token_creation_replacements",
    "resolve_counter_placement_replacements",
    "resolve_zone_change_replacements",
    "collect_zone_change_replacement_effects",
    "capture_zone_change_replacement_snapshot",
    "collect_counter_placement_replacement_effects",
    "collect_damage_replacement_effects",
    "collect_damage_result_replacement_effects",
    "collect_draw_replacement_effects",
    "collect_draw_instruction_replacement_effects",
    "collect_draw_restrictions",
    "current_draw_permission",
    "collect_life_change_replacement_effects",
    "collect_untap_step_participations",
    "current_untap_step_plan",
    "log_applied_zone_replacements",
    "prepare_zone_change_replacement",
    "prepare_zone_change_replacement_batch",
    "prepare_zone_change_replacement_snapshot",
    "PreparedZoneChange",
    "ZoneReplacementError",
    "describe_runtime_handler",
    "runtime_component_inventory",
    "runtime_component_registry_fingerprint",
    "validate_runtime_handler_descriptors",
    "ENCHANT_FRAGMENT_HANDLER_ID",
    "TYPED_ENCHANT_FRAGMENT_HANDLER_ID",
    "BATTLE_CRY_FRAGMENT_HANDLER_ID",
    "BUSHIDO_FRAGMENT_HANDLER_ID",
    "DECLARATION_COST_FRAGMENT_HANDLER_ID",
    "DECLARATION_REQUIREMENT_FRAGMENT_HANDLER_ID",
    "DECLARATION_RESTRICTION_FRAGMENT_HANDLER_ID",
    "FLANKING_FRAGMENT_HANDLER_ID",
    "EXALTED_FRAGMENT_HANDLER_ID",
    "MELEE_FRAGMENT_HANDLER_ID",
    "PROTECTION_FRAGMENT_HANDLER_ID",
    "BattleCryAbilityFragmentHandler",
    "BushidoAbilityFragmentHandler",
    "DeclarationCostAbilityFragmentHandler",
    "DeclarationRequirementAbilityFragmentHandler",
    "DeclarationRestrictionAbilityFragmentHandler",
    "ExaltedAbilityFragmentHandler",
    "FlankingAbilityFragmentHandler",
    "MeleeAbilityFragmentHandler",
    "TypedEnchantAbilityFragmentHandler",
    "fragments_from_descriptors",
]
